---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    # https://fluxcd.io/flux/faq/#how-to-patch-coredns-and-other-pre-installed-addons
    kustomize.toolkit.fluxcd.io/ssa: merge
