---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-nfs-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd-nfs-storage
  resources:
    requests:
      storage: 2Gi
