---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-local-data
  namespace: home
  # annotations:
  #   volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd-nfs-storage # local-path
  resources:
    requests:
      storage: 2Gi
