---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homeassistant-secrets
  namespace: home
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: homeassistant-secrets
    template:
      engineVersion: v2
      data:
        # Home Assistant
        LATITUDE: "{{ .LATITUDE }}"
        LONGITUDE: "{{ .LONGITUDE }}"
        WORK_LATITUDE: "{{ .WORK_LATITUDE }}"
        WORK_LONGITUDE: "{{ .WORK_LONGITUDE }}"
        GABIS_WORK_LATITUDE: "{{ .GABIS_WORK_LATITUDE }}"
        GABIS_WORK_LONGITUDE: "{{ .GABIS_WORK_LONGITUDE }}"
        # Postgres Init
        POSTGRES_DB: home_assistant
        POSTGRES_HOST: postgres-rw.development.svc.cluster.local
        POSTGRES_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.development.svc.cluster.local/home_assistant"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: hass
    - extract:
        key: cloudnative-pg
