# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:Nu765QgUqEAklrpVy3Py1/aVe7NNTbo0rMMytsqQ+PT+DTloWxLmKk05i0q/6WXG3vx2Hq8hZv45FeZ8S2InQRaPagm/mLy+nfUnqrpSVmyDpFl9EY722ZssQdhgZiif24nguk4ouDOnEKbDevqQz+G077AxSzUAFfJa5TiBuaN+p5e3t8gfQuw5WhN60khIHPXmgPQDuzmyubSqr9eC4F86JRjbiVn0IGYpRwAqO/gjKGMmh9fwQjCbw7/AvpHzva27L3lpJ8BxzXvU/hOr8jTeQPm3ktwGvEvDf72nob9qzFz8ul7xBMQCHZZvjqrSM09syBPJ1Lw9YlW+55OcaFG/ws6CI4al6pBU+gjJRWYAm9cnymMy2jaxfrmqr5FVgPMA3bNciTRGOZj641dVFJtXwVopUj25YzosqVPMkkHCK/wxXWOJ3CXV8Nl/87a9BhnUxdbyI0drc3O4LWLK63bRtlyZ6FPdse6kNoSDKfGju5PE12R8EFw3S8wAZrGdx9vRaGH6nkupy2drqIdROLmYz0mBMt+QBM/0jJmbX+uSPlB/0pPzJRZhFwMtVHLXjBLmgA+wbnFDjGzFYwyyX9c6EuJx4m8l5T0Vdznm1y9iaaELa9nqRw5/lBEu/ZSKYSR7N3vnSeUcLxgTHAkdw4RlXV2GUbSee+rjt3mWI0hTdASiPNQrraBOmkX5ONaR33AkWqK8s4An9zCnGUD4K0kQJReVuVFDFThbQgp1tm4S7Ya21C3uUIU6fuTqoQbOGyPzmAJyj5iIPrE1tRRqogPDUFSvhgkb4QSv6NlR45BwRFrz4jq9mAgySU3ZVCn+/8WNS46ArQpYfr5uUuAsQl0AaRAj,iv:atlex2YmOoAnLG/PP28IHjUhmDn3UM0ZVCLumP9zE/A=,tag:Hg9J8lxMDXHxgCrmjT7h5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWDhzdlpFamNtVHN3UzJ1
            UXNIRENNdXFNc1poOFkzQTdFOG1nR2xLUUY0CndMTzlEVmNVQnB1NllVWkYrY01x
            WEJyc2FQMEhxNjBzSm5rcDFKazZkUXMKLS0tIEdrSlEwUSsrc0hIbjZMaGxXeFBB
            dTUybG9ZUUc5V0gyQU1jdCtqcWlMcU0KVv8Xk4UuYN311IYGSnnD/yQJEe9Btm5L
            Ne1e6m9BZ7VULIri7KuQT1Gbrenf+yM5Nssz2ufsFdUdnpFy3dywIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T17:34:28Z"
    mac: ENC[AES256_GCM,data:+td7GxTX9e5nHabb5CumI9irHu2F4/Ddz6SrXEGrTRuot2ZJW/lT+T0epd2DmL+T2B832VUn0olCZWg8GjkUwsCeBSFoJc33fWibWrcPKjHYhf03M/C0zDyywv42z6Yk5/wN+PakS8rSZq+PTbSycIbXrqkMEdNeR338yNhCr8k=,iv:Rn+HctewCP0PcJjSWiYqRjxyURSBWoMEYwAr4Bs8aiE=,tag:c7UcR8Ne1XH5rBI6sMnlng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
