---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./rbac.yaml
  - ./daemonset.yaml
labels:
  - pairs:
      kustomize.toolkit.fluxcd.io/prune: disabled
      # https://fluxcd.io/flux/faq/#how-to-patch-coredns-and-other-pre-installed-addons
      kustomize.toolkit.fluxcd.io/ssa: merge
