apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:8+Buh6HUKSbEqwMnLrbFFgq5vDY1aTSL7Rw8dZLYTIXLRrTKastvdw==,iv:zTIze7rIbwPgghrOwRAjcw2Lax4OTFxPsYdw4t2DMfQ=,tag:uGau6ZbWPsOJhnM4aqGHiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUGpNaCsvQ2ZJN0o4eWtL
            RDlmSkNMdzJFanVvSDhNWTh0bEhmci9rSGdBCkl3WTErMzgva2k0UENhSm4rYXhv
            L2NBNzZBb3JvT2NYalhoTGFTU05RRlUKLS0tIHQrYXNUY0dPUUJDN3ZJNFdxMkdY
            OFFXRGFFVmNIZ1BqVU9Hb0lnT0xQTDQKaoI/6L0petNj6dW08bFWHjl2h9JwC6t+
            MjjIr6CBX0ND2PO6SH+9hcwCJwur/vQMi7Po0C1Aj5p5ZcCG6rdEWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-17T11:11:36Z"
    mac: ENC[AES256_GCM,data:YUesGDkoU0Qu2cjnWJsdfCDTvrkCgM/aTagIuJYIsK+Kmrc0kP4K74AoB69GJeWuejgsVEoNu9CRKwkLKdJc1V2em1H9Ugh+WtrU6O8uoWwOOgeXwHwth4tFZAgjWGDlffO28IKlKS1YV0y0ODXh+Oli7XWV7VidvjdzpEgC7Vo=,iv:UgQn5kFtM0Fz68J1665jQT6tmFZcfIYjyt+o4Cx/72o=,tag:dU4dg8aLDFfQhylG7BGD5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
