---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: "ahuffman.resolv"
      resolv_nameservers:
        - "127.0.0.53"
      resolv_search: []
      resolv_options:
        - "edns0 trust-ad"
