apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:TzrNl1im78H7i/iTxPGeyPmrd07dELvr+wvKdcAPobceHAwCckkvdt1oe8xVtIevwZdOoTBeYf2+UQ7A,iv:aBsznhFWyy2EWDDqbE/5+/+9qET7VOndXiq6QrVMv/M=,tag:k8lppbwhmODb77g3RkcZKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL3dKRE4vVTltN2xxM0Fa
            dVVVWVZHYUlSU2UzbnlZYlFISGxLOHBPcnpRCnYyN1Y2b0NIbkVhN3VHcm5jbHVT
            U2pxOSsvWG0ybDBCNHpITXRGZ205SkUKLS0tIFJVRVN1cm14V2xZVGpTZGMrNnZX
            QVdRVXFUdG5XOEVzOFZZdW5tK015KzAKMKWC27UEbUgPK9CBrSUuNVykR3PR1O6B
            GY/cueABQ9YLAwBEKj3iE/CznK9hFZUgwJVakpI9l+QT21pH+hPoyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-21T06:19:27Z"
    mac: ENC[AES256_GCM,data:pw/kXyRO0uVm/BLucJSCf+wYuFr7PyyshZaePHi5DuA8Ko2vgNMN/BXwpiB0ixTWVNkYqy0PhfNw8dWKBcnTYkWklCi5fW3sGA+heNE7vTKXFFLDnauuQYGsoYXDx77TKJsvs2DuV3s6qCAkt+bgqekcP0CylGYcjQO9Tlo4CgI=,iv:ysm0IyvxxgsvlVhsBIn75MFjmydx6+aPVmHJOri6ZO8=,tag:tLvTAs3YVhbEgV9DQyYElg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
