apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:iGozt5UNrGhEGgnYhmAYfumcPE8U4FYczfqaQ85s2/DqIIH7aTIub8MWkLy6KYFHLrOWpMXsSl4bzlnU,iv:DQeCewEuEG8hmx1ZkEvaPD4RVZfNZSiwimtdcmXTryg=,tag:b1NxWNxR1xhbkHpWJ/ZUKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2ynvs6f5sug5hf5yzd3dedd4yusth2rwxg77xxllg8kgcdd2f8sw965ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL3dKRE4vVTltN2xxM0Fa
            dVVVWVZHYUlSU2UzbnlZYlFISGxLOHBPcnpRCnYyN1Y2b0NIbkVhN3VHcm5jbHVT
            U2pxOSsvWG0ybDBCNHpITXRGZ205SkUKLS0tIFJVRVN1cm14V2xZVGpTZGMrNnZX
            QVdRVXFUdG5XOEVzOFZZdW5tK015KzAKMKWC27UEbUgPK9CBrSUuNVykR3PR1O6B
            GY/cueABQ9YLAwBEKj3iE/CznK9hFZUgwJVakpI9l+QT21pH+hPoyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-17T11:11:37Z"
    mac: ENC[AES256_GCM,data:uy0gdZP6Q4UAni36X2nKTq3xCoZXrG8uU5MrYNraU3dPDNQVCPh+zHXa9vncvfsibWI3nrjqAkbYJOkYqb8XAea4YTVON7Fuph7TRfwVnZy004tECF56zjSdqAaF1SuBXHJDHILD8cXEQBODcegP4cdEOMEpn+pPl6uYSpLPjoo=,iv:4s5HnpzZhbo2kEKoRF9r6YAEkuBWcWlFYZ/cMtmzKis=,tag:NdW0vfxqxubsfuc5/eiQDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
