# Loads default set of integrations. Do not remove.
default_config:

recorder:
  purge_keep_days: 5
  db_url: !env_var POSTGRES_URL

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
    - 127.0.0.1
    - ::1
    - 10.0.0.201

homeassistant:
  name: Home
  latitude: !env_var LATITUDE
  longitude: !env_var LONGITUDE
  elevation: 141
  # icon: mdi:castle
  unit_system: metric
  currency: GBP # https://en.wikipedia.org/wiki/ISO_4217#Active_codes
  country: GB # https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements
  temperature_unit: C
  time_zone: "Europe/London"
  # external_url: "https://hass.fabricesemti.net/"
  # internal_url: "http://homeassistant.local:8123"
  # allowlist_external_dirs:
  #   - "/usr/var/dumping-ground"
  #   - "/tmp"
  # allowlist_external_urls:
  #   - "http://images.com/image1.png"
  # media_dirs:
  #   media: "/media"
  #   recordings: "/mnt/recordings"
  # legacy_templates: false

# updater:
#   include_used_components: true
system_health:
# stream:

zeroconf:

zone:
  - name: Work
    latitude: !env_var WORK_LATITUDE
    longitude: !env_var WORK_LONGITUDE
    radius: 100
    icon: mdi:briefcase

  - name: Gabi's Work
    latitude: !env_var GABIS_WORK_LATITUDE
    longitude: !env_var GABIS_WORK_LONGITUDE
    radius: 100
    icon: mdi:briefcase

# camera:
#   - platform: xiaomi_cloud_map_extractor
#     host: 10.3.0.2
#     token: !env_var ROBOROCK_TOKEN
#     username: nikola@milojevic.me
#     password: !env_var ROBOROCK_XIAOMI_PASSWORD
#     draw: ["all"]
#     attributes:
#       - calibration_points
#     map_transformation:
#       scale: 1
#       trim:
#         top: 17
#         bottom: 20
#         left: 25
#         right: 20

# telegram_bot:
#   - platform: polling
#     api_key: !env_var TELEGRAM_API_KEY
#     allowed_chat_ids:
#       - !env_var TELEGRAM_CHAT_ID

# notify:
#   - platform: telegram
#     name: telegram
#     chat_id: !env_var TELEGRAM_CHAT_ID

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml
