---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/London"
  KUBE_VIP_ADDR: "10.0.0.254"
  METALLB_LB_RANGE: "10.0.0.200-10.0.0.220"
  METALLB_K8S_GATEWAY_ADDR: "10.0.0.200"
  METALLB_INGRESS_ADDR: "10.0.0.201"

  # Storage [NAS] settings
  NAS_SERVER: 10.0.0.2
  NAS_PATH_MEDIA: /docker-memedia
  # NAS_PATH_MEDIA: /PersistentVolumeClaims/Media
  # NAS_PATH_MINIO: /PersistentVolumeClaims/MiniIO

  # General settings
  PUID: "1000"
  PGID: "1000"

  # Service addresses
  SVC_CNPG_IP: 10.0.0.202
  SVC_GITEA_IP: 10.0.0.203
  SVC_HASS_IP: 10.0.0.204

  MULTUS_IOT_HASS: "10.3.0.205"
