---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: cloudflared
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    cloudflared:
      tunnel: b605e9b7-5647-47fc-9af4-a24904bf05d2 # ? cloudflared tunnel list

      ingress:

        - hostname: httpbin.fabricesemti.net
          service: http://httpbin.default:443

        - hostname: hello.fabricesemti.net
          service: hello_world

        - hostname: hajimari.fabricesemti.net
          service: http://hajimari.default.svc.cluster.local:3000
          
        - hostname: '*.${SECRET_DOMAIN}'
          service: https://ingress-nginx-controller.networking
          originRequest:
            noTLSVerify: true          

        - service: http_status:404
