---
# https://external-secrets.io/v0.4.4/api-externalsecret/
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-secrets
  namespace: development
spec:

# RefreshInterval is the amount of time before the values reading again from the SecretStore provider
  # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h" (from time.ParseDuration)
  # May be set to zero to fetch and create it once
  refreshInterval: "1h"

  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitea-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        email: "{{ .email }}"
        password: "{{ .password }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: gitea
