---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-nfs-data
  namespace: development
  # annotations:
  #   volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd-nfs-storage # local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgresql-data
  namespace: development
  # annotations:
  #   volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hdd-nfs-storage # local-path
  resources:
    requests:
      storage: 10Gi
